[package]
name = "efcp"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
bytes = "0.4.12"
