[package]
name = "efcp"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
byteorder = "1.3.2"
bytes = "0.4.12"
failure = "0.1.5"

[workspace]
members = [
  "channel",
  "dtp",
  "dtcp",
]
