[package]
name = "efcp"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
disco = { git = "https://github.com/rust-p2p/disco" }
dtp = { path = "../dtp" }
dtcp = { path = "../dtcp" }
