[package]
name = "test-channel"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
bytes = "0.4"
channel = { path = "../channel" }
rand = "0.7.2"

[dev-dependencies]
async-std = "0.99"
